version: 0.0
os: linux
files:
  - source: /
    destination: /opt/roommitra/website # <- this service’s path on EC2
permissions:
  - object: /opt/roommitra/website
    pattern: '**'
    owner: appuser
    group: appuser
    mode: 755
    type: [file, directory]
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      runas: root
      timeout: 120
  AfterInstall:
    - location: codedeploy/after_install.sh
      runas: appuser
      timeout: 900
  ApplicationStop:
    - location: codedeploy/stop.sh
      runas: appuser
      timeout: 120
  ApplicationStart:
    - location: codedeploy/start.sh
      runas: appuser
      timeout: 300
